graph TD
    A((Living Things))
    B((Animals))
    C((Plants))
    D((Dogs))
    E((Cows))
    F((Herbs))

    B -->|is a| A
    C -->|is a| A
    D -->|is a| B
    E -->|is a| B
    F -->|is a| C
    E -->|eat| F